# Generated by Django 4.2.1 on 2023-05-23 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 9, 54, 34, 658241, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ChekTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finded_question', models.PositiveIntegerField(default=0)),
                ('user_passed', models.BooleanField(default=False)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_main.test')),
            ],
        ),
        migrations.CreateModel(
            name='ChekQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(help_text='Например: A', max_length=1)),
                ('true_answer', models.CharField(help_text='Например: A', max_length=1)),
                ('is_true', models.BooleanField(default=False)),
                ('checktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_main.chektest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_main.question')),
            ],
        ),
    ]
